### ISSUE TITLE
Redirecting to cart after adding one product to the cart

### ISSUE THREAD

**Issue by AvishekGhost** [Ninad99/GiftKart#21]
Currently when the user adds a product to the cart, the page is redirected to the cart, resulting in a bad user experience. An alternative would be to update the cart quantity and show it on the navbar.

**Comment by Ninad99** [comment]
Also, there is no option to select the quantity of products to add to the cart. I'll work on adding that too.

**Comment by Ninad99** [comment]
Fixed in #23
