### ISSUE TITLE
Create rider portal

### ISSUE THREAD

**Issue by Ninad99** [Ninad99/GiftKart#39]
Similar to the admin views, a rider portal needs to be created for it on a separate endpoint

**Comment by Ninad99** [comment]
@AvishekGhost Can you work on this?

I've created the basic rider model and setup the routes and controllers.

Have a look at 7769c47dfe5ce63360b69b289e690e534638a693 to see the changes I made.

**Comment by AvishekGhost** [comment]
I'll continue further

**Comment by Ninad99** [comment]
> I'll continue further

Noice
